global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "ufc_ranker_rules.yml"

scrape_configs:
  # UFC Ranker Backend
  - job_name: 'ufc-ranker-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # UFC Ranker Celery Worker
  - job_name: 'ufc-ranker-celery'
    static_configs:
      - targets: ['celery_worker:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (системные метрики)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
